### ISSUE TITLE
INT pin

### ISSUE THREAD

**Issue by d-a-v** [njh/W5500MacRaw#1]
Hello,

I was looking for a raw ethernet driver to interface w5500 with lwIP (on esp8266) and found your repo, thanks !
I can't find any reference to the INT pin, so I assume that you are exclusively polling SPI to know when a packet has come to the interface, do you confirm it needs not be connected ?

Thanks

**Comment by njh** [comment]
Ah! Getting W5500 to work with LWIP is very interesting.

Yes, that is correct, I have not been using the INT pin at all and have just been polling SPI.

I imagine you would get better latency if you did use Interrupts. But my applications have not required it.

nick.

**Comment by d-a-v** [comment]
Thanks! I ordered the chips, and I will keep you informed

**Comment by d-a-v** [comment]
I have it working with lwIP on esp8266 thanks to your MacRaw driver :)
I am doing this by inheriting a slightly modified version of your class.
I will propose a PR for this if you don't mind.
